#ifndef PMU_EXAMPLES_H
#define PMU_EXAMPLES_H

#define MaxSamplesPerAtoD 1000000

#define ERR_PMU_EXAMPLES_OFFSET						-17000
#define ERR_PMU_EXAMPLES_WRONGCARDID				-1	+	ERR_PMU_EXAMPLES_OFFSET
#define ERR_PMU_EXAMPLES_CARDHANDLEFAIL				-2	+	ERR_PMU_EXAMPLES_OFFSET

#define ERR_PMU_EXAMPLES_MEAS_EARLY					-100	+	ERR_PMU_EXAMPLES_OFFSET
#define ERR_PMU_EXAMPLES_OUTPUT_ARRAY_TOO_SMALL		-110

#endif